export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';

export const GET_MOVIE = 'GET_MOVIE';
export const MOVIE_LOADING = 'MOVIE_LOADING';
export const CLEAR_CURRENT_MOVIE = 'CLEAR_CURRENT_MOVIE';
export const GET_MOVIES = 'GET_MOVIES';

export const DELETE_MOVIE = 'DELETE_MOVIE';
